message("-- Setting shared compile options: " ${PROJECT_NAME})

include(FetchContent)
Set(FETCHCONTENT_QUIET FALSE)
set(FETCHCONTENT_UPDATES_DISCONNECTED ON)
if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
	message("-- Setting dependency directory to C:/fc to avoid path limit.")
	set(FETCHCONTENT_BASE_DIR "C:/fc" CACHE PATH "" FORCE)
endif()

set(CMAKE_C_STANDARD 23)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS ON)
set(CMAKE_DISABLE_PRECOMPILE_HEADERS OFF)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE TRUE)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_DEBUG FALSE)
set(CMAKE_CXX_COMPILER_LAUNCHER ccache)

include(ProcessorCount)
ProcessorCount(_core_count)
if(_core_count EQUAL 0)
  set(_core_count 1)
endif()
set(CMAKE_BUILD_PARALLEL_LEVEL _core_count)
set(ENV{CMAKE_BUILD_PARALLEL_LEVEL} "${_core_count}")
message(STATUS "CMAKE_BUILD_PARALLEL_LEVEL set to $ENV{CMAKE_BUILD_PARALLEL_LEVEL}")

