message("-- Setting shared compile options: " ${PROJECT_NAME})

set(CMAKE_C_STANDARD 23)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS ON)
set(CMAKE_DISABLE_PRECOMPILE_HEADERS OFF)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE TRUE)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_DEBUG FALSE)

set(CMAKE_BUILD_PARALLEL_LEVEL 16)
set(CMAKE_CXX_COMPILER_LAUNCHER ccache)

